name: pytests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Pytest
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v3
      id: pyinstall
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install clang llvm libelf-dev libpcap-dev gcc-multilib build-essential linux-libc-dev
    - name: Build libbpf
      run: |
        cd dependencies/libbpf/src/
        make
        cd ../../../
      env:
        OBJDIR: ../../../src/bpfmaps/libbpf/
    - name: Install requirements
      run: | 
        sudo ${{ steps.pyinstall.outputs.python-path }} -m pip install -r requirements.txt
        sudo ${{ steps.pyinstall.outputs.python-path }} -m pip install -r requirements-dev.txt
        sudo ${{ steps.pyinstall.outputs.python-path }} -m pip install --upgrade build
    - name: Run tests and collect coverage
      run: sudo ${{ steps.pyinstall.outputs.python-path }} -m pytest --cov --cov-report xml .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
    - name: Build package
      if: startsWith(github.ref, 'refs/tags')
      run: sudo ${{ steps.pyinstall.outputs.python-path }} -m build
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
        verbose: true
        print_hash: true
