name: Release package

on: 
  workflow_run:
    workflows: ["pytests"]
    branches:
      - 'main'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}


jobs:
  build:
    runs-on: ubuntu-latest
    name: Release package to mypi
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install clang llvm libelf-dev libpcap-dev gcc-multilib build-essential linux-libc-dev
        sudo mkdir dist
    - name: Build libbpf
      run: |
        cd dependencies/libbpf/src/
        make
        cd ../../../
      env:
        OBJDIR: ../../../src/bpfmaps/libbpf/
    - name: Install requirements
      run: | 
        sudo /opt/hostedtoolcache/Python/3.10.4/x64/bin/python3 -m pip install -r requirements.txt
        sudo /opt/hostedtoolcache/Python/3.10.4/x64/bin/python3 -m pip install -r requirements-dev.txt
        sudo /opt/hostedtoolcache/Python/3.10.4/x64/bin/python3 -m pip install --upgrade build
    - name: Build package
      run: sudo /opt/hostedtoolcache/Python/3.10.4/x64/bin/python3 -m build
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags') # only push to official pypi if we tag the commit
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
        verbose: true
        print_hash: true
